### ISSUE TITLE
Consistent Handling of Emoji's in Messages

### ISSUE THREAD

**Issue by 49Indium** [UQComputingSociety/uqcsbot-discord#100]
I have noticed that there are a lot of regex variants to remove/ignore emotes from discord messages. These should be placed into a central function (maybe in `command_utils.py`).

Some examples:
 - `haiku.py`: `"<a?:.+?:[0-9]+?>"`
 - `yelling.py`: `":[\w\-\+\~]+:"` (does links as well)
 - `cowsay.py`: `"<a?:\w+:\d+>"`
 
> Wow, if I had a nickel for every time I [found a regex for replacing discord emotes] ... I'd have ~~two~~[three] nickels - which isn't a lot, but it's weird that it happened ~~twice~~[thrice].

**Comment by andrewj-brown** [comment]
Closing as a subset of #120.
