### ISSUE TITLE
Snailrace v2.0

### ISSUE THREAD

**Issue by lcox74** [UQComputingSociety/uqcsbot-discord#108]
Dear UQCS members,

I write to you to express my concern for the highly popular, and beloved `snailrace`. Members have not been kind to her causing random bugs to plague the enjoyment of many sarcastic users.

With that being said, the UQCS Discord bot is about to get even more exciting with the introduction of `snailrace v2.0`! This major update to the existing snail racing feature will bring a complete snail racing and management system to the bot, allowing users to not only race their snails but also own, trade, breed, and train them.

**Key Features:**

- **Snail Ownership:** Users will be able to own and name their own snails, which they can then use to participate in races or breed with other snails.
- **Breeding and Training:** Users will be able to breed their snails to create new snails with improved stats and personalities. They will also be able to train their snails to increase their speed, stamina, and other stats.
- **Trading System:** Users will be able to trade their snails with other users using the bot's new snail trading system.
- **Achievements:** Users can earn achievements for various milestones and accomplishments within the snail racing world.
- **Profile Cards:** Each user will have a snail racing profile card that displays their stats, achievements, and badges.
- **Improved Race System:** The updated race system will include features like varying distance single races and tournaments.

**Examples of Use:**

- *Jimmy 'McCafe' D* owns several snails and has been training them for weeks to improve their stats. He enters them into a multi-snail race with other users and watches eagerly as they compete for the top spot.
- *Hax 'Master' Andrew* has a rare snail that she wants to trade for a different type of snail. She uses the bot's trading system to find a user who has the snail she wants and successfully completes the trade.
- *Hi Phil* has been participating in snail races for a while and has accumulated several achievements. He proudly displays his badges on his snail racing profile card for all to see.

With the introduction of Snailrace v2.0, the UQCS Discord bot will become an even more engaging, chaotic and interactive platform for our community. Get ready to own, race, and trade your snails like never before!

Please check out the [development spec](https://github.com/lcox74/uqcsbot-discord/blob/snailrace/uqcsbot/snailrace/README.md) which is currently looking for critique even though `snailrace` is perfect and will be perfect forever.

Sincerely,

The Snailrace Team.

**Comment by lcox74** [comment]
Amend spec to:

- [ ] Poke fun at single racers
- [ ] Be specific with race entrant timeouts

**Comment by andrewj-brown** [comment]
Considering snailrace has moved to [its own repo](https://github.com/lcox74/snailrace/), closing this issue.
