### ISSUE TITLE
Poke fun at single snail races

### ISSUE THREAD

**Issue by JamesDearlove** [UQComputingSociety/uqcsbot-discord#118]
Related to #108, uqcsbot should poke fun at people who run and therefore win single snail races. 

Examples: 
> The race has finished! lcox74 has won! But it was against themselves, that was a little sad

> The race has finished! JimmyD has won! Suspicious there was no other snails though

> The race has finished! Andrew has won! But wait, it was a false start

**Comment by bradleysigma** [comment]
My suggestion would be that the 10s countdown doesn't start until there are at least two snails in the race. (Also, make the 10s countdown reset each time a snail joins.)

**Comment by lcox74** [comment]
@bradleysigma If the timeout counter doesnt start until a second racer has joined then it will leave opportunity for races to forever remain open.

The spec for **snailrace v2.0** has an autofill planned by default after the entrance time has elapsed. But It can be turned off with `dont-fill`. I'll amend it to be specific about countdown times and will do 10s countdown reset after each entrant (until full), but I'll make it timeout for single racer.

**Comment by lcox74** [comment]
I've updated the doc.

https://github.com/lcox74/uqcsbot-discord/blob/snailrace/uqcsbot/snailrace/docs/race.md
