### ISSUE TITLE
Allocation of Bot Tokens

### ISSUE THREAD

**Issue by JamesDearlove** [UQComputingSociety/uqcsbot-discord#12]
We need to sort a way to allocate bot tokens to devs for the testing server. We cannot store them in the repo as allegedly tokens will be disabled by Discord automatically for security. Unlike Slack tokens, these could potentially cause more harm then just our own server so we need to be careful.

Some potential ways this could be done:
* New bot command that DMs a user a token for use.
  * Tokens stored in the DB and randomly allocated for requesters.
* Manually given out by committee or pinned in a testing channel.

**Comment by TomCranitch** [comment]
I would like to have a look at this soon. I think the first solution is best, and I have a feeling that we are unlikely to get anyone wanting bot tokens for nefarious purposes so we can likely get away without doing any sort of user verification for example (as I assume the only server that should be running the testing bots is the testing server)

**Comment by JamesDearlove** [comment]
I agree, was tinkering with this briefly last week and seems that the first solution is easiest. Not sure if it’s actually worth storing who’s got what token. All tokens can be revoked through the dev portal worst comes to worst, and joining bots to new servers _should_ be restricted.

Was thinking the best thing to do is to DM a user a random token from the pool by default.

**Comment by JamesDearlove** [comment]
I'm taking this on, work currently under `improve-dev` branch

**Comment by JamesDearlove** [comment]
For now, I'm going to unassign myself from this as I'm not really finding the time for working on it atm. If someone wants to take up the reigns, my code and readme rewrite for improving the dev experience for the bot is in `improve-dev` branch. I haven't written any code for distributing tokens.

**Comment by JamesDearlove** [comment]
A decision has been made to recommend contributors to acquire their own tokens, as per the updated [README section on env variables](https://github.com/UQComputingSociety/uqcsbot-discord#environment-variables).

We've made this decision due to the risks of sharing around these tokens, and the difficulty of attempting to get around Discord's don't share token features built right into the client.
