### ISSUE TITLE
!listchannels should highlight unjoined channels

### ISSUE THREAD

**Issue by katrinafyi** [UQComputingSociety/uqcsbot-discord#13]
It'd be useful if the !listchannels list showed some indication of whether or not you were in a channel. Some options off the top of my head are:
- display unjoined channels separately, or
- add an icon or label to unjoined channels.

**Comment by TomCranitch** [comment]
I think it might be useful if this was turned on with a flag, in case people wanted to list channels without listing all of the channels they are in

**Comment by JamesDearlove** [comment]
Closing as we're getting rid of our managed channel system for Discord's version
