### ISSUE TITLE
Whatsdue enhancements

### ISSUE THREAD

**Issue by jenseni-git** [UQComputingSociety/uqcsbot-discord#145]
There have been a couple of suggestions on how to improve the whatsdue cog. I'll just collate a couple of them here

- [x] Sortby and order argument. Collate and sort the assessment list by a particular field (i.e. date, course code, etc.) In the order ASC/DESC
- [x] timescale argument. Only show assessments due in the next (n) weeks/days
- [x] displayLinks arg. If this argument is passed as true, display links to the requested ECPs at the bottom of the message

**Comment by 49Indium** [comment]
I'll just add that #142 fixes the first point.

Could we turn that list into a todo list add I'll try to get these done by this week.
