### ISSUE TITLE
uqcsbot poll

### ISSUE THREAD

**Issue by jenseni-git** [UQComputingSociety/uqcsbot-discord#165]
New cog idea: poll.

/poll will take in between 3 and 11 arguments.
- The first argument will be the polling question to be proposed to voters
- The second and third (as a minimum) up to the 11th argument will be the polling answers for users to select.
- When the function is called, the bot will send the argument question, then format each possible response with the relevant numerical emoji 1-n (0 being 10) displayed next to the relevant answer option. The bot will then react with the relevant numerical emojis.

Possible pain points:
- Message overflow (Should this be handled by multiple messages or an error; how may this effect the below idea).

Extensibility idea: an addtional 'ping me' argument of a time. At the time as inputted, the bot will ping the sender again, and reference the original poll to remind the poller that the poll is now finished.

**Comment by andrewj-brown** [comment]
Potentially a good use-case for using interaction buttons instead of reactions, which is the way that bots are "supposed" to do stuff like this.

**Comment by 49Indium** [comment]
Closing this, as [Discord is rolling out a native poll feature](https://support.discord.com/hc/en-us/articles/22163184112407-Polls-FAQ).
