### ISSUE TITLE
Migrate to a different Discord Python library

### ISSUE THREAD

**Issue by JamesDearlove** [UQComputingSociety/uqcsbot-discord#30]
As discord.py development was discontinued a few months ago, a few replacements have popped up. It would be good to be able to take advantage of Slash commands and upcoming API features so we will need to look at migrating to a new library. This issue is to track what to move to and discussion around that.

Alternative libraries:

https://github.com/nextcord/nextcord
https://github.com/Pycord-Development/pycord

Any additional libraries and suggestions are welcome!

**Comment by jtc** [comment]
Interesting update today: [On Resuming discord.py Development](https://gist.github.com/Rapptz/c4324f17a80c94776832430007ad40e6)

**Comment by JamesDearlove** [comment]
Great to see the project has resumed development.

No changes to what library we use is now required, we will wait for v2 of discord.py
