### ISSUE TITLE
Advent of code integration

### ISSUE THREAD

**Issue by lindenwells** [UQComputingSociety/uqcsbot-discord#32]
## Event times
```javascript
const times = [
{
    week: 1,
    begin: '2021-12-01T15:00:00+10:00',
    end: '2021-12-08T15:00:00+10:00',
    draw:'2021-12-10T15:00:00+10:00',
},
{
    week: 2,
    begin: '2021-12-08T15:00:00+10:00',
    end: '2021-12-14T15:00:00+10:00',
    draw:'2021-12-16T15:00:00+10:00',
},
{
    week: 3,
    begin: '2021-12-14T15:00:00+10:00',
    end: '2021-12-20T15:00:00+10:00',
    draw:'2021-12-22T15:00:00+10:00',
},
{
    week: 4,
    begin: '2021-12-20T15:00:00+10:00',
    end: '2021-12-26T15:00:00+10:00',
    draw:'2021-12-30T15:00:00+10:00',
}
]

```
I know it's a weird way to notate, but it's what made sense to me.
All events happen at 15:00:00+10:00 (3PM AEST) because that happens to be midnight CST.
The reason for 6 day weeks etc is that we wanted to do a weekly giveaway, but 7 doesn't divide 25 (25 being the "days of Christmas").

## Roles to be created
- 2021 Advent of code participant
- 2021 Advent of Code ping (purely used to receive updates)
- 2021 Advent of Code first/second year participant
- 2021 Advent of Code winner

## When and how should each role be pinged?
The bot should ping people with the ping role at the beginning of every week and the end of week 4. Beginning of week pings should say:
- If an AOC week has just finished, mention it and the upcoming draw time.
- Say the beginning, end and draw times for the upcoming week.

The ping at the end of week 4 should say:
- When week 4 of AOC finished and when prizes will be drawn.

The draw pings should:
- Say what week has just finished.
- Pick one random first year participant
- Pick one random participant (check it's not the first year that was picked)
- Ping the winners
- Give the winners a discord role?
- If applicable, say when next week's prize will be drawn and wish participants luck with the current week.

**Comment by TomCranitch** [comment]
I've started working on this in the aoc-comp branch. My implementation is a bit different but stores the winners in the db and fetches the winners based on the leaderboard (as opposed to discord pings).

One issue we have is that there's no connection between discord handles and aoc usernames.

We also need a way to work out who the first/second years are (I haven't worked on this yet)

**Comment by JamesDearlove** [comment]
My two cents on those issues:

Potentially registering your display name with your Discord profile via a command is a solution for linking. Unfortunately, AoC can be logged in with four OAuth providers, so we can’t just get people to link their GitHub to Discord.

In terms of first/second years, you can take advantage of the roles that we put in place on Discord. You’ll just have to make sure that these are actually accurate, and people have done it. Alternatively, you _could_ connect to the membership db, however that is currently not really possible with the current infrastructure. Also I’d discourage against membership db being accessible with the bot for the just in case scenario.

**Comment by TomCranitch** [comment]
This was added in #31
