### ISSUE TITLE
Bring back welcome dm

### ISSUE THREAD

**Issue by JamesDearlove** [UQComputingSociety/uqcsbot-discord#38]
With the old bot, when someone joined the server they would receive a DM from UQCSbot with a reminder about channels. You can see the old implementation here: https://github.com/UQComputingSociety/uqcsbot-discord/blob/main/unimplemented/welcome.py

**Comment by TomCranitch** [comment]
It'd be good to push people to post in #intros. The old welcome message was possibly also too long, and I'm not sure if people were actually reading it all

**Comment by 49Indium** [comment]
We now have the full discord course introduction, so this is no longer needed.
