### ISSUE TITLE
IDs are silly

### ISSUE THREAD

**Issue by andrewj-brown** [UQComputingSociety/uqcsbot-discord#87]
We should have a universal system for handling (well, avoiding) IDs in the bot. Possibly an env variable.

**Comment by JamesDearlove** [comment]
I actually have a thing pre-implemented in [bot.py](https://github.com/lcox74/uqcsbot-discord/blob/70f7fbbf00fb4905420e30501ad447d3fb87bbd1/uqcsbot/bot.py#L14) that handles this, but it only really supports the main server and our private testing server.

**Comment by andrewj-brown** [comment]
Yeah, Isaac pointed that out to me. I think it'd be better to switch to an env variable that people can arbitrarily set; plus then we can use server.channels instead of bot.get_all_channels()

**Comment by andrewj-brown** [comment]
this has moved to misc-dev branch and the pr #94

**Comment by andrewj-brown** [comment]
with the merging of #94, we are now certified 100% ID-free*

*Bot made with equipment that processes ~~peanuts~~ IDs and traces may remain.
